Remove old image references.
circleci/circleci-docs pull request #4713
Opened 2020-09-14 22:00 UTC by felicianotech

2020-09-21 17:21 UTC, teesloane commented on jekyll/_cci2/concepts.md
> +## Image
I'm glad we're adding this to concepts.

2020-09-21 17:22 UTC, teesloane reviewed
Thanks for making this PR. Is it still in Draft?

2020-09-21 17:22 UTC, teesloane commented on jekyll/_cci2/executor-types.md
> +The following example uses an image and enables [Docker Layer Caching]({{ site.baseurl }}/2.0/docker-layer-caching) (DLC) which is useful when you are building Docker images during your job or Workfl
```suggestion
The following example uses an image and enables [Docker Layer Caching]({{ site.baseurl }}/2.0/docker-layer-caching) (DLC) which is useful when you are building Docker images during your job or workflow. **Note:** You must open a support ticket to have a CircleCI Sales representative contact you about enabling this feature on your account for an additional fee.
```

2020-09-22 14:12 UTC, felicianotech commented
It's ready now. I needed to add/update the Docker versions section as well.

2020-09-22 14:26 UTC, teesloane requested changes

2020-09-22 14:26 UTC, teesloane commented on jekyll/_cci2/building-docker-images.md
> +	      version: 19.03.12
I think indentation might be off here?

2020-09-22 14:26 UTC, teesloane commented on jekyll/_cci2/concepts.md
> +An image is a packaged system that has the instructions for creating a running container.
```suggestion
An image is a packaged system that has instructions for creating a running container. 
```

2020-09-22 14:26 UTC, teesloane commented on jekyll/_cci2/concepts.md
> + The Primary Container is defined by the first image listed in [`.circleci/config.yml`]({{ site.baseurl }}/2.0/configuration-reference/) file. This is where commands are executed for jobs using the D
```suggestion
 The Primary Container is defined by the first image listed in a [`.circleci/config.yml`]({{ site.baseurl }}/2.0/configuration-reference/) file. This is where commands are executed for jobs using the Docker or machine executor. The Docker executor spins up a container with a Docker image. The machine executor spins up a complete Ubuntu virtual machine image. See the [Choosing an Executor Type]({{ site.baseurl }}/2.0/executor-types/) document for a comparison table and considerations.
```

2020-09-22 14:27 UTC, teesloane commented
> It's ready now. I needed to add/update the Docker versions section as well.

Awesome, thanks! Just put up a few suggestions and then should be good to merge.

2020-09-24 14:52 UTC, felicianotech commented on jekyll/_cci2/building-docker-images.md
> +	      version: 19.03.12
Checking

2020-09-24 14:55 UTC, felicianotech commented on jekyll/_cci2/building-docker-images.md
> +	      version: 19.03.12
Correct. There was a tab.

2020-09-24 14:59 UTC, felicianotech commented
Updated with suggestions.

2020-09-24 18:24 UTC, teesloane approved these changes

2020-09-25 13:59 UTC, felicianotech commented
Thanks for your help @teesloane.

2020-09-25 13:59 UTC, merged