Add Orbs registry results to search
circleci/circleci-docs pull request #4793
Opened 2020-10-02 00:37 UTC by tfe

Per [CIRCLE-27855](https://circleci.atlassian.net/browse/CIRCLE-27855), redesigns the search results page and adds a results category for Orbs from the Orbs registry.

This also depends on and includes changes from #4754. This will be simpler to review if we merge that first and then update this branch from master; otherwise this PR will include changes from both.

2020-10-09 15:29 UTC, janedotbiz requested changes
Is it possible to have the subnav background colour go full width so that the highlighted search result doesn't peak out from under the side of it? I see the underline is not full-width in the design so that might be a bit tricky.
![Screen Shot 2020-10-09 at 10 39 20 AM](https://user-images.githubusercontent.com/5113432/95599693-66ce6b80-0a1f-11eb-8ddb-8545c0fc7814.png)

The very first result is covering up the subnav underline on hover:
![Screen Shot 2020-10-09 at 10 34 35 AM](https://user-images.githubusercontent.com/5113432/95599863-a432f900-0a1f-11eb-9190-4d487ec40655.png)

I noticed the highlighted search result doesn't quite line up with the width and alignment of the subnav (underline)
![Screen Shot 2020-10-09 at 10 34 15 AM](https://user-images.githubusercontent.com/5113432/95599985-cd538980-0a1f-11eb-817a-7801999a27bc.png)

2020-10-09 15:29 UTC, janedotbiz commented on jekyll/_sass/_subnav.scss
> +}
The first list item is shown as flush left in the design.

```css
.component.subnav li:first-child {
  margin-left: 0;
}
```

Before:
![Screen Shot 2020-10-09 at 11 20 06 AM](https://user-images.githubusercontent.com/5113432/95601613-b31aab00-0a21-11eb-9568-f9ef054e9551.png)

After:
![Screen Shot 2020-10-09 at 11 21 39 AM](https://user-images.githubusercontent.com/5113432/95601633-b6ae3200-0a21-11eb-9461-6a50968e64a7.png)

Additionally, the design has everything (search input, first subnav item, and results) all with the same left alignment, but more indented (relative to search icon placement) than what's here.

Design:
![Screen Shot 2020-10-09 at 9 42 11 AM](https://user-images.githubusercontent.com/5113432/95601763-ebba8480-0a21-11eb-8435-9cdecb0e1d4d.png)

2020-10-09 15:29 UTC, janedotbiz commented on jekyll/_sass/_instantsearch.scss
> +        width: 20px;
The reset icon is 14px x 14px in the design, and also a light grey colour.
![Screen Shot 2020-10-09 at 9 39 21 AM](https://user-images.githubusercontent.com/5113432/95600580-5f5b9200-0a20-11eb-9b83-1162e6c0e49d.png)
Design:
![Screen Shot 2020-10-09 at 11 13 35 AM](https://user-images.githubusercontent.com/5113432/95600678-81551480-0a20-11eb-854c-6ff6ef0d7678.png)

2020-10-09 15:29 UTC, janedotbiz commented on jekyll/_sass/_instantsearch.scss
> +    background-color: #EEF2F5;
The design has this as a dark blue (`#19639A`) with a 5% opacity.
Using transparency allows the contrast of the `mark` background colour compared to the result background colour to be more similar between the hover and non-hover state of the result (white vs grey background)

2020-10-09 15:37 UTC, janedotbiz commented on jekyll/_sass/_subnav.scss
> +}
Oh also, the non-active items in the subnav in the design are bolded, but gray; 
rather than a regular weight and black(ish)

2020-10-10 02:15 UTC, tfe commented
OK, I think I've resolved everything except for the width of the subnav bottom border when in fixed position, which I ran out of time on. Let me know if you see a way to fix that; all the things I tried didn't work.

2020-10-14 16:07 UTC, janedotbiz commented
![Screen Shot 2020-10-14 at 11 56 27 AM](https://user-images.githubusercontent.com/5113432/96015243-5a7a5200-0e15-11eb-9b4e-039400bd657e.png)

Are you seeing this too? When I first type in a search query, Orbs is highlighted in the menu, even though the Docs results are what are displayed, and the scroll position is slightly off. Once I scroll or click in the subnav things appear to be normal.

2020-10-14 19:02 UTC, tfe commented
@janedotbiz I chased down that behavior to the subnav JS not accounting for it being hidden on initial page load, as it is for docs search (all of its position calculations are incorrect because hidden element positions are all 0). Here's a PR to make it robust to that (https://github.com/circleci/circleci.com-shared/pull/2), and I'll follow it up with a PR here that triggers the new event introduced there upon showing results.

2020-10-14 22:35 UTC, janedotbiz approved these changes
Thank you!

It'd be nice to address the subnav underline at some point, but I don't think that's worth holding this up.

2020-10-15 14:35 UTC, teesloane commented
Thanks @janedotbiz and @tfe! I will merge this in today (and presumably can close #4754 following that).

2020-10-15 14:36 UTC, merged