Include further description of command line values
circleci/circleci-docs pull request #4873
Opened 2020-10-24 00:26 UTC by orangegrove1955

# Description
I have included further descriptions of the values in the command line to more easily understand and follow these setup instructions

# Reasons
When attempting to follow these instructions to set up a new namespace for the first time, the arguments were unclear, especially considering these are getting started docs. It would be helpful to include this brief description for first time authors to understand what they need to input to the command line

2020-10-27 14:48 UTC, teesloane requested changes
G

2020-10-27 14:48 UTC, teesloane commented on jekyll/_cci2/orb-author-intro.md
> +where `name` is the namespace you wish to claim, `vcs-type` is the type of your version control system (i.e. `github` or `bitbucket`), and `org-name` is the name of your organisation
```suggestion
where `name` is the namespace you wish to claim, `vcs-type` is the type of your version control system (i.e. `github` or `bitbucket`), and `org-name` is the name of your organization.
```

2020-10-27 14:48 UTC, teesloane commented on jekyll/_cci2/orb-author-intro.md
> +where `name` is the namespace you wish to claim, `vcs-type` is the type of your version control system (i.e. `github` or `bitbucket`), and `org-name` is the name of your organisation
Good call. We should have this information here. I have made one small suggestion which you can commit using GitHub's interface; then we will be all set to merge.

Thank you for contributing!

2020-10-28 00:18 UTC, orangegrove1955 commented
@teesloane Thanks for the suggestion, I have committed it and believe this PR is ready to merge

2020-11-09 17:55 UTC, teesloane approved these changes

2020-11-09 17:58 UTC, merged