added private orb content
circleci/circleci-docs pull request #5056
Opened 2021-01-28 23:59 UTC by thomasr8

Added section on the difference between public and private orbs.

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2021-01-29 06:30 UTC, tim-circleci commented
LGTM. Will there be a separate sections for the CLI commands we introduced?

2021-02-02 05:09 UTC, thomasr8 commented
> LGTM. Will there be a separate sections for the CLI commands we introduced?

Hi @tim-circleci : Is there a place where @annabaker and I can get a list of these commands to add to the documentation?

2021-02-02 06:51 UTC, tim-circleci commented
The command for adding private orbs and the command for validating private orbs are in the documentation as well:

Creating in an existing namespace,` circleci orb create --private <ns/orb>` will create a private orb

Validating: `circleci config validate --orgSlug <your-org-slug> <path/to/config.yml>`

Next week we will also add a command for listing private orbs specifically. I'll ping you when that is done.

2021-02-02 15:01 UTC, teesloane requested changes
A few wording / style suggestions as well as a syntax fix.

2021-02-02 15:01 UTC, teesloane commented on jekyll/_cci2/orb-intro.md
> +Orbs are reusable chunks of configuration published to the [CircleCI Orb Registry](https://circleci.com/developer/orbs). Traditionally, these orbs are authored by individuals and then published to th
```suggestion
Using a private orb enables you to author an orb while ensuring the following:
```
The beginning of the document already states what is being stated here, I would remove it.

2021-02-02 15:01 UTC, teesloane commented on jekyll/_cci2/orb-intro.md
> +Public orbs are used by most users when authoring and publishing orbs to the [CircleCI Orb Registry](https://circleci.com/developer/orbs). When authoring a public orb, you are enabling all other user
```suggestion
Public orbs are used by most users when authoring and publishing orbs to the [CircleCI Orb Registry](https://circleci.com/developer/orbs). When authoring a public orb, you are enabling all  CircleCI users to use your orb in their own configurations.
```

2021-02-02 18:42 UTC, thomasr8 commented on jekyll/_cci2/orb-intro.md
> +**Note:** Private orbs are currently only available if you are on the https://circleci.com/pricing[Scale Plan]. Please reach out to your sales representative for information on how to sign up for the
Fixed

2021-02-02 19:29 UTC, teesloane approved these changes

2021-02-02 19:32 UTC, merged