Added caveat for use of Shared Libraries
circleci/circleci-docs pull request #5057
Opened 2021-01-29 05:10 UTC by makotom

# Description
Added a caveat that we do not support Shared Libraries.

# Reasons
Increasing number of feedbacks refer to the use of Shared Libraries.

2021-01-29 14:15 UTC, teesloane requested changes
Just a small wording change, otherwise good to go.

2021-01-29 14:15 UTC, teesloane commented on jekyll/_cci2/jenkins-converter.md
> +* Only a single Jenkinsfile is accepted per request. Namely, [Shared Libraries](https://www.jenkins.io/doc/book/pipeline/shared-libraries/) will not be resolved, and resulting `config.yml` can be inc
```suggestion
* Only a single Jenkinsfile is accepted per request. Namely, [Shared Libraries](https://www.jenkins.io/doc/book/pipeline/shared-libraries/) will not be resolved, and the resulting `config.yml` may be incomplete. Note that under certain cases the converter does not raise errors even if there are unresolvable Shared Libraries.
```

2021-01-29 18:24 UTC, thomasr8 approved these changes

2021-01-29 23:16 UTC, dsayling approved these changes

2021-02-01 12:23 UTC, teesloane approved these changes

2021-02-01 12:42 UTC, merged