Update orb-intro.md
circleci/circleci-docs pull request #5066
Opened 2021-02-03 17:27 UTC by thomasr8

One minor change to CLI command.

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2021-02-03 17:29 UTC, tim-circleci requested changes
there is a hyphen missing still should be `--org-slug`

2021-02-03 17:37 UTC, thomasr8 commented
> there is a hyphen missing still should be `--org-slug`

Fixed

2021-02-03 17:39 UTC, tim-circleci approved these changes

2021-02-03 20:21 UTC, teesloane approved these changes

2021-02-04 16:30 UTC, annabaker approved these changes

2021-02-18 23:24 UTC, closed without merging