[WEB-95] Search Results for mobile
circleci/circleci-docs pull request #5121
Opened 2021-03-02 21:06 UTC by tfe

This adds a mobile version of the search result category subnav, as well as some page layout structure improvements to enable that change.

Those changes resolve some long-standing Bootstrap grid misuse in the header and search bar:

1. Search query bar and results container had a row without   accompanying columns (should just be a container sans row). The   query bar CSS had manually implemented (and incomplete for mobile)   margins to compensate, which are now removed.

2. The header logo was absolutely positioned, resulting in it appearing   outside its surrounding column/container (too far left). This commit   removes that, allowing it to be positioned on the left edge of its   container where it will align with other containers on the page,   such as the search query bar and results container.

3. The search results item wrapper had negative margins to allow space   around the hover/highlight background color, however this resulted   in horizontal scrolling on narrow screens because it was larger than   the gutter width. Note: there is still some horizontal scrolling   present on narrow screens being caused by something in the footer.

2021-03-02 22:02 UTC, janedotbiz requested changes

2021-03-02 22:02 UTC, janedotbiz commented on jekyll/_sass/_subnav.scss
> +    li {
On the smallest screens (under 370px wide) the "Images" tab wraps, reducing the margin from 24px would help
![Screen Shot 2021-03-02 at 4 26 48 PM](https://user-images.githubusercontent.com/5113432/109721076-e26cb880-7b78-11eb-83f2-3db497b98aad.png)
.

2021-03-02 22:02 UTC, janedotbiz commented on jekyll/assets/css/navbar.css
> -    left: 0;
The left nav is now out of alignment (too far left) with the search bar and logo:
![Screen Shot 2021-03-02 at 4 25 54 PM](https://user-images.githubusercontent.com/5113432/109721189-092aef00-7b79-11eb-9fcc-3f49b08f0ab4.png)

2021-03-02 22:04 UTC, tfe commented
Something isn't right here in general, because you shouldn't be seeing the mobile version of the sidebar nav. I also can't reproduce the left nav alignment thing.

Can you try clearing the jekyll build cache (`jekyll reset` I think), rebuild, and look again?

2021-03-02 22:08 UTC, tfe commented
OK I take some of that back, I am getting the mobile sidebar appearing on desktop now behind the desktop version. I'll get that fixed up.

2021-03-02 22:58 UTC, tfe commented
OK, I resolved that issue and the rest should clear up with a cache reset and rebuild on your end.

2021-03-03 16:38 UTC, janedotbiz approved these changes

2021-03-03 16:38 UTC, merged