Runner in Server [CIRCLE-33129]
circleci/circleci-docs pull request #5155
Opened 2021-03-17 11:18 UTC by kkowalski

# Description
Adding changes needed when setting up a Runner for Server.

# Reasons
https://circleci.atlassian.net/browse/CIRCLE-33129

2021-03-17 18:44 UTC, thomasr8 requested changes

2021-03-17 18:44 UTC, thomasr8 commented on jekyll/_cci2/runner-server.md
> +When creating namespaces. resource classes and tokens, the CLI needs to be configured to connect to the Server
```suggestion
When creating namespaces, resource classes and tokens, the CLI needs to be configured to connect to the Server 
```

2021-03-17 18:44 UTC, thomasr8 commented on jekyll/_cci2/runner-server.md
> +deployment either via `--host HOSTNAME` and `--token TOKEN` flags or CLI's config file.
```suggestion
deployment either via `--host HOSTNAME` and `--token TOKEN` flags, or the CircleCI CLI's configuration file.
```

2021-03-17 18:44 UTC, thomasr8 commented on jekyll/_cci2/runner-server.md
> +When setting up a Runner the configuration file should include `host` property.
```suggestion
When setting up a Runner, the configuration file should include `host` property.
```

2021-03-17 18:44 UTC, thomasr8 commented on jekyll/_cci2/runner-server.md
> +Specific server version works with specific runner version. The table below presents the mapping.
```suggestion
A specific server version works with a specific runner version. The table below presents the mapping.
```

2021-03-18 01:18 UTC, heug commented
@thomasr8 could i get a heads up when this is ready for translation please? thank you!

2021-03-18 17:16 UTC, glenjamin reviewed
Execution content looks fine to me, should perhaps link to the rest of the cloud runner docs?

2021-03-22 15:14 UTC, kkowalski commented
It will be under Runner section so customer should be able to to see other runner related docs in the tree next to this article

2021-03-22 18:45 UTC, thomasr8 approved these changes
Looks good!

2021-03-22 19:28 UTC, glenjamin commented
I wonder if this needs a note to say it’s not available in 3.0 and to
contact us?

On Mon, 22 Mar 2021 at 18:45, thomasr8 ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Looks good!
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/circleci/circleci-docs/pull/5155#pullrequestreview-617870027>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABE52FHQTV5N2NSAEM5JQ3TE6F4JANCNFSM4ZKMLLXA>
> .
>

2021-03-23 17:29 UTC, nsmith5 approved these changes

2021-03-24 12:41 UTC, annabaker commented on jekyll/_data/sidenav.yml
> +          link: 2.0/runner-server/
```suggestion
        - name: Runner in Server
          link: 2.0/runner-server/
        - name: Runner FAQs
          link: 2.0/runner-faqs/
```

2021-03-24 12:43 UTC, annabaker approved these changes

2021-03-24 12:43 UTC, annabaker commented on jekyll/_data/sidenav.yml
> +          link: 2.0/runner-server/
Looks good -- just rearranged the sidebar links so FAQ is at the bottom. This is fine to be merged now that Server 3 docs are public.

2021-03-24 12:50 UTC, glenjamin commented
The key thing to note here is that Runner isn't available in the current version of Server - it will only be available in special preview versions until the next release.

2021-03-24 13:00 UTC, kkowalski commented
@annabaker could you add this note that @glenjamin mentioned ? I talked with @thomasr8 about it.

2021-03-26 08:53 UTC, merged