arm resources updates
circleci/circleci-docs pull request #5183
Opened 2021-03-24 18:00 UTC by thomasr8

Added FAQs section to page.

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2021-03-24 19:45 UTC, annabaker approved these changes

2021-03-25 19:39 UTC, teesloane commented
@thomasr8 it appears the content you are putting into the .md file is asciidoc, you'll need to convert that before merging.

2021-03-25 19:40 UTC, teesloane requested changes

2021-03-25 19:40 UTC, teesloane commented on jekyll/_cci2/arm-resources.md
> +toc::[]
Prob shouldn't be here - should be handled by the toc in the markdown file.

2021-03-25 19:40 UTC, teesloane commented on jekyll/_cci2/arm-resources.md
> +=== How do I get access to the Arm preview?
should be markdown headings

2021-04-05 06:24 UTC, closed without merging