Patch local build
circleci/circleci-docs pull request #5191
Opened 2021-03-29 07:43 UTC by ganezasan

# Description

Changed the docker image on docker-compose to fix an issue in the local build. This is because we bumped the ruby version to `2.7.2`, and the previous image is no longer applicable. 

# Reasons
Slack: https://circleci.slack.com/archives/C0KBNJGRH/p1616802657027600

cc: @mvxt

2021-03-29 14:01 UTC, teesloane approved these changes

2021-03-29 14:04 UTC, teesloane requested changes

2021-03-29 14:04 UTC, teesloane commented
This is good to merge; tested with success. One request for a small change to the readme. Thanks @ganezasan !

2021-03-29 17:11 UTC, mvxt approved these changes

2021-03-30 00:14 UTC, ganezasan commented on README.md
> +Building the static Jekyll site can run without installation by using Docker.
@teesloane Thank you for your suggestion! I merged it!

2021-03-30 14:13 UTC, merged