[SERVER-1069] add prereqs and post migration steps
circleci/circleci-docs pull request #5290
Opened 2021-04-28 20:33 UTC by lloydChris

# Description
Add more details around 2.19 to 3.0 migrations.
- Warnings around proper prerequisites
- When to use new resources vs copying config over from 2.19
- debugging tips

2021-04-29 14:18 UTC, robinsturmeit commented on jekyll/_cci2/server-3-install.adoc
> +NOTE: If this instance is being set up in preparation for a migration from 2.19, it is recommended to use a new 0Auth application, not the same one used in 2.19.
```suggestion
NOTE: If this instance is being set up in preparation for a migration from 2.19, it is recommended to use a new OAuth application, not the same one used in 2.19.
```

2021-04-29 14:18 UTC, robinsturmeit requested changes
Small typo, apart from that excellent! :)

2021-04-29 18:25 UTC, MikeyYeahYeah approved these changes

2021-04-30 08:40 UTC, robinsturmeit approved these changes

2021-04-30 11:18 UTC, brianoh1979 approved these changes
Looks good to me!

2021-04-30 14:31 UTC, merged