Fixes for path-filtering example
circleci/circleci-docs pull request #5306
Opened 2021-05-03 19:06 UTC by annabaker

# Description
The path-filtering example had some inconsistencies in nomenclature. I also added some more descriptive comments to the exmaple config.

2021-05-03 19:26 UTC, thomasr8 approved these changes

2021-05-03 19:26 UTC, teesloane requested changes

2021-05-03 19:26 UTC, teesloane commented on jekyll/_cci2/configuration-cookbook.md
> +# workflow calls a specific job defined above, in the jobs section.
```suggestion
# here we specify our workflows, most of which are conditionally executed based upon pipeline parameter values. 
# Each workflow calls a specific job defined above, in the jobs section.
```
Should this `each` maybe be on the next line?

2021-05-03 19:26 UTC, teesloane commented on jekyll/_cci2/configuration-cookbook.md
> +# workflow calls a specific job defined above, in the jobs section.
Just a small nit - but looks good otherwise!

2021-05-03 19:26 UTC, teesloane commented on jekyll/_cci2/configuration-cookbook.md
> +# workflow calls a specific job defined above, in the jobs section.
Just a small nit - but looks good otherwise!

2021-05-04 15:33 UTC, teesloane approved these changes

2021-05-04 15:44 UTC, merged