[SERVER-1169] details on how to configure an external vault instance
circleci/circleci-docs pull request #5428
Opened 2021-06-10 19:15 UTC by lloydChris

This is a redo of https://github.com/circleci/circleci-docs/pull/5415 which was incorrectly based off of main

# Description
Server now supports Externalizing Vault. Add documentation so people know how to do it.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

https://circleci.atlassian.net/browse/SERVER-1169

Please critique the formatting. The internal/external part is particularly bad

2021-06-10 19:15 UTC, MikeyYeahYeah approved these changes

2021-06-11 09:27 UTC, robinsturmeit requested changes
Two minor corrections

2021-06-11 09:27 UTC, robinsturmeit commented on jekyll/_cci2/server-3-install.adoc
> +*External* will not install the default Vault instance with the CircleCI application.  Select this option if using an existing Vault instance.  Will require the user to configure the following settin
```suggestion
*External* will not install the default Vault instance with the CircleCI application.  Select this option if using an existing Vault instance.  You need to configure the following settings:
```

2021-06-11 09:27 UTC, robinsturmeit commented on jekyll/_cci2/server-3-install.adoc
> +. Token: The Vault token to be used by CircleCI.  The following example shows how to create a token with the recommend policy
```suggestion
. Token: The Vault token to be used by CircleCI.  The following example shows how to create a token with the recommended policy
```

2021-06-11 14:04 UTC, robinsturmeit approved these changes

2021-06-15 05:51 UTC, annabaker approved these changes

2021-06-15 05:51 UTC, merged