Update _config.yml
circleci/circleci-docs pull request #5438
Opened 2021-06-15 20:11 UTC by nathanfishcircleci

https://circleci.atlassian.net/browse/SERVER-1213

# Description
older versions have issues with minio

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2021-06-15 21:09 UTC, nsmith5 requested changes

2021-06-15 21:09 UTC, nsmith5 commented on jekyll/_config.yml
> +      kotsversion: 1.43
Version must be greater than 1.43 I believe. Can confirm that 1.44 worked for Pawan who has faced the original issue.

```suggestion
      kotsversion: 1.44
```

2021-06-16 18:06 UTC, nathanfishcircleci commented
@annabaker @nsmith5 i made an additional update. 1.44.1 based on this mornings conversation with replicated.

2021-06-23 15:07 UTC, robinsturmeit approved these changes

2021-06-23 19:54 UTC, closed without merging

2021-06-23 19:54 UTC, nathanfishcircleci commented
@rosieyohannan  This can be closed. Another PR is open for this change.