Server/3.1/update private loadbalancer webhooks preview
circleci/circleci-docs pull request #5487
Opened 2021-07-05 21:47 UTC by rosieyohannan

A proxy must be set up if a github.com/server user with private frontend load balancer wants to have webhooks work. This note points to the setting in the CCI app.

2021-07-05 21:56 UTC, rosieyohannan commented on jekyll/_cci2/server-3-operator-load-balancers.adoc
> +====
```suggestion
[WARNING]
==== 
**Webhooks:** If you choose to make the frontend load balancer private, the following conditions must be met, dependent on VCS, for webhooks to work: 

* **GitHub Enterprise** – your CircleCI server installation must be in the same internal network as GHE. 
* **github.com** – set up a proxy for incoming webhooks. This setting can be found under **Admin Settings** > **System Settings** > **Override webhook host URL** from the CircleCI app.
====
```

2021-07-06 09:25 UTC, robinsturmeit requested changes
I think something like this is a little more precise

2021-07-06 09:25 UTC, robinsturmeit commented on jekyll/_cci2/server-3-operator-load-balancers.adoc
> +* **github.com** – set up a proxy for incoming webhooks. This setting can be found under **Admin Settings** > **System Settings** > **Override webhook host URL** from the CircleCI app.
```suggestion
* **github.com** – set up a proxy for incoming webhooks and set it as override for the webhook host URL. This setting can be found under **Admin Settings** > **System Settings** > **Override webhook host URL** from the CircleCI app.
```

2021-07-06 10:00 UTC, rosieyohannan commented on jekyll/_cci2/server-3-operator-load-balancers.adoc
> +* **github.com** – set up a proxy for incoming webhooks. This setting can be found under **Admin Settings** > **System Settings** > **Override webhook host URL** from the CircleCI app.
Thanks Robin!

2021-07-06 10:34 UTC, robinsturmeit approved these changes

2021-07-06 10:43 UTC, merged