Update references to legacy images
circleci/circleci-docs pull request #5797
Opened 2021-10-15 19:25 UTC by kbatuigas

# Description
Updated legacy image references to the corresponding next-gen images (generally, `circleci` -> `cimg`).

More references will be updated as more next-gen images are released. For some I'm still waiting on clarification as to whether they need more than just the name swap.

# Reasons
Legacy images will be deprecated this year on 12/31. Some of these legacy images already have their next-gen counterparts; others are still being built.

2021-12-21 04:29 UTC, kbatuigas commented
> @kbatuigas Can you please remove your changes to the `package-lock.json`? Content changes should not trigger changes to dependencies. Thanks!

Hi @rsylvian , I wasn't sure how to trace back the changes I made to `package-lock.json`, but I figured I'd just have you re-review in case that's now been resolved.

2022-01-05 00:01 UTC, rsylvian commented
Thanks, @kbatuigas!

2022-01-05 00:02 UTC, rsylvian approved these changes
Approving because I originally requested changes about the package-lock. I'm not qualified to approve the actual content changes so feel free to ask other people on that matter 🙌

2022-01-19 01:28 UTC, felicianotech requested changes

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +    - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +  version: 2
This line isn't needed with config v2.1.

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +    - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +  version: 2
This line isn't needed in v2.1 config.

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run : mvn test
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run : mvn test
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run: npm install
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run: npm install
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/code-coverage.md
> +      - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:28 UTC, felicianotech commented on jekyll/_cci2/config-intro.md
>        - run:
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-20 16:05 UTC, felicianotech approved these changes

2022-01-20 16:36 UTC, merged