Update images from circleci to cimg
circleci/circleci-docs pull request #5828
Opened 2021-10-21 15:22 UTC by devinmarieb

# Description
These image updates were the ones that were fairly straightforward (I think anyway). 

# Reasons
Legacy images are being replaced by convenience images, and we are replacing where appropriate.

2022-01-06 18:21 UTC, devinmarieb commented
For whoever reviews this, there are only a few commits that matter to the images specifically (the others were to resolve build/pipeline issues and to add tabs for code blocks). These are the commits that need to be reviewed for the image updates:

- Update images from circleci to cimg _(further updates on this page based on clarification in the following two commits)_
- Legacy image swap for postgres
- Update adv-config.md

2022-01-19 01:33 UTC, felicianotech requested changes

2022-01-19 01:33 UTC, felicianotech commented on jekyll/_cci2/adv-config.md
> +      - run: mkdir test-reports
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:33 UTC, felicianotech commented on jekyll/_cci2/adv-config.md
> +      - run: mkdir test-reports
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:33 UTC, felicianotech commented on jekyll/_cci2/adv-config.md
> +      - image: cimg/node-browsers
This is missing a tag. Something like:

`- image: cimg/node:17.0-browsers`

2022-01-19 01:33 UTC, felicianotech commented on jekyll/_cci2/adv-config.md
> +      - run: sudo apt-get install postgresql-client-9.6
If we're going to use a browser testing example and include the orb, we need to run the orb. Something here like:

`- run: browser-tools/install-browser-tools`

2022-01-19 01:33 UTC, felicianotech commented on jekyll/_cci2/pipeline-variables.md
> +      - image: cimg/node:latest
latest is not a tag

maybe :17.0

2022-01-20 17:49 UTC, devinmarieb commented
@felicianotech I have made the changes and double checked for additional places that had the same needs in these files. Thank you!

2022-01-31 16:26 UTC, felicianotech approved these changes

2022-01-31 16:33 UTC, merged