language-python-update
circleci/circleci-docs pull request #5998
Opened 2021-12-01 23:27 UTC by thomasr8

# Description
Replaced legacy image reference to next-gen image

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2022-01-19 01:37 UTC, felicianotech requested changes

2022-01-19 01:37 UTC, felicianotech commented on jekyll/_cci2/language-python.md
> +      - image: cimg/postgres:14.0.0 # an example of how to specify a service container
`14.0.0` doesn't exist. `14.0` does.

2022-01-19 01:37 UTC, felicianotech commented on jekyll/_cci2/language-python.md
> +      - image: cimg/postgres:14.0.0
`14.0` not `14.0.0`

2022-01-19 09:08 UTC, thomasr8 commented on jekyll/_cci2/language-python.md
> +      - image: cimg/postgres:14.0.0 # an example of how to specify a service container
Fixed

2022-01-19 09:08 UTC, thomasr8 commented on jekyll/_cci2/language-python.md
> +      - image: cimg/postgres:14.0.0
Fixed

2022-01-26 13:56 UTC, felicianotech approved these changes

2022-01-26 22:34 UTC, merged