Update project-walkthrough.md
circleci/circleci-docs pull request #6016
Opened 2021-12-06 02:30 UTC by thomasr8

# Description
replaced legacy images with next-gen images.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2021-12-06 13:06 UTC, rosieyohannan commented on jekyll/_cci2/project-walkthrough.md
> +      - image: cimg/python:3.6.2-stretch-browsers
This is extracted from the demo app linked to in the intro text. AFAIU the demo app will need updating to use a next gen image first. Also Browser teating using a different image variant now, as mentioned in the migration guide: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034#browser-testing-4

I feel like some of these changes are a little more involved that straight swap to `cimg`.

2021-12-06 13:06 UTC, rosieyohannan commented on jekyll/_cci2/project-walkthrough.md
> +      - image: cimg/python:3.6.2-stretch-browsers
@felicianotech ^^

2021-12-08 23:40 UTC, rosieyohannan commented on jekyll/_cci2/project-walkthrough.md
> +      - image: cimg/python:3.6.2-stretch-browsers
https://github.com/CircleCI-Public/circleci-demo-python-flask/blob/da7d6585eeac60722e04b10f612acb327e9cd72c/.circleci/config.yml#L30

2022-01-19 01:43 UTC, felicianotech requested changes
Only namespace changes were made here. We still need to do tags.

2022-01-31 19:07 UTC, felicianotech approved these changes

2022-01-31 19:11 UTC, merged