Update language-go.md
circleci/circleci-docs pull request #6017
Opened 2021-12-06 02:37 UTC by thomasr8

# Description
replaced references to legacy images to next-gen images

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

2021-12-08 23:37 UTC, rosieyohannan commented on jekyll/_cci2/language-go.md
> +      - image: cimg/golang:1.16
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034#deprecated-images-3 `golang` -> `go`

2022-01-19 01:43 UTC, felicianotech requested changes

2022-01-19 01:43 UTC, felicianotech commented on jekyll/_cci2/language-go.md
> +      - image: cimg/postgres:9.6-alpine
-alpine needs to go.

2022-01-19 01:43 UTC, felicianotech commented on jekyll/_cci2/language-go.md
> +      - image: cimg/postgres:9.6-alpine
-alpine needs to go.

2022-01-19 21:43 UTC, thomasr8 commented on jekyll/_cci2/language-go.md
> +      - image: cimg/golang:1.16
fixed

2022-01-19 21:43 UTC, thomasr8 commented on jekyll/_cci2/language-go.md
> +      - image: cimg/postgres:9.6-alpine
removed

2022-01-19 21:43 UTC, thomasr8 commented on jekyll/_cci2/language-go.md
> +      - image: cimg/postgres:9.6-alpine
removed

2022-01-31 16:36 UTC, felicianotech approved these changes

2022-01-31 18:36 UTC, merged