[DD-277]: Header - Remove the Line next to CircleCI - Docs
circleci/circleci-docs pull request #6038
Opened 2021-12-08 21:03 UTC by tshen815

**Ticket:** [DD-277](https://circleci.atlassian.net/browse/DD-277)

# Changes

- Removed divider line in header

# Description
Remove the line next to CircleCI in the header of the docs to be consistent with the circelCI.com website to provide a consistent UI experience for the users

# Before

![Screen Shot 2021-12-08 at 1 02 17 PM](https://user-images.githubusercontent.com/57234605/145283873-1299ff29-5bc2-4a1f-8973-a34e203acbe2.png)

# After
![Screen Shot 2021-12-08 at 1 02 57 PM](https://user-images.githubusercontent.com/57234605/145283957-d264e061-655b-4b7c-9125-12987d0cb2f9.png)

2021-12-08 21:26 UTC, rsylvian requested changes
We should update the spacing so it's consistent with outer:

![Screen Shot 2021-12-08 at 1 25 57 PM](https://user-images.githubusercontent.com/1449325/145286872-52073e8c-f837-4e72-ba37-4454dec2e5bc.png)

2021-12-08 21:26 UTC, rsylvian commented on src/styles/_global-nav.scss
> +      // border-left: solid 1px #aaaaaa;
```suggestion
```

✂️

2021-12-09 15:27 UTC, teesloane approved these changes

2021-12-09 16:53 UTC, ccgeller approved these changes
Minor comment, PR shows same pictures for before and after.

2021-12-10 23:11 UTC, rsylvian approved these changes

2021-12-10 23:22 UTC, merged