Add: batch resizes images in docs.
circleci/circleci-docs pull request #6215
Opened 2022-01-18 19:28 UTC by teesloane

[Ticket](https://circleci.atlassian.net/browse/DD-335)

🖼 - add resizing of images to python find_big_images.py script.
👾 - squishes their bits and bytes down to size. (anything beyond 1920x in width or height gets limited to 1920px.)
🤙 - uses sweet thumbnail feature to avoid skewed images.

2022-01-20 02:39 UTC, chantelle11 commented on scripts/find_big_images.py
> +resize_image()
Now that the code is run should resize_image() be default commented like write and print?

2022-01-20 02:45 UTC, chantelle11 approved these changes
Looks good to me! 🧚✌️💕

2022-01-20 03:06 UTC, nramabad requested changes
so the thing I'm seeing here is that for some of these images, shrinking the image dimensions is actually increasing the image file size? I'm guessing this is down to how png does things like anti-aliasing(?)

I'm sorta skeptical if we're going to see benefits, given [according to Google](https://web.dev/lcp/#how-is-an-element's-size-determined) LCP of an image is typically determined by the size of an image as displayed in the viewport. it would be good run Lighthouse on `master-preview` vs `<your branch>-preview` on a page URL that has an image touched in this PR. (preferrably 2 - one with the decrease file size and one with the increase file size)

I ran it ooc and these were my results:
After: <img width="1292" alt="Screen Shot 2022-01-19 at 7 02 46 PM" src="https://user-images.githubusercontent.com/42252054/150264751-202814af-f9f8-467b-a85f-fea41f524093.png">
Before: <img width="1304" alt="Screen Shot 2022-01-19 at 7 02 37 PM" src="https://user-images.githubusercontent.com/42252054/150264755-209d491f-dbba-41b1-b6ab-b2ebc430e9cb.png">

Seems like in this example the image size increases and the LCP score does too (although I admit Lighthouse scores are always a bit suspect and more ballpark compared to something like PageSpeed)

If you're able to demonstrate the improvement and add it to the PR description, i think that would be much better than flying blind on 90 file changes.

2022-01-20 03:36 UTC, nramabad commented
Here's the apples to apples Lighthouse on Desktop since it's a bit more relevant.

Before: ![image](https://user-images.githubusercontent.com/42252054/150267542-ad5528e4-fe07-4b60-88e8-bd3e29a21b7b.png)
After: ![image](https://user-images.githubusercontent.com/42252054/150267598-ad829655-bd31-426d-beb0-414bbedad544.png)

The contrast in LCP is more stark here since Desktop unlike Mobile, the image is above the fold content.

2022-01-21 14:28 UTC, teesloane commented
Wow, interesting insights @nramabad . Thanks for quantifying these changes. I'll do some more testing today. Interestingly, I've realized that pngs in all ascidocs seem to not be working in the preview.

2022-01-21 16:21 UTC, teesloane commented
Found [this thread](https://stackoverflow.com/questions/33892585/why-does-resizing-a-jpeg-image-using-pil-increases-file-size) that points at some possible reasons file sizes are increasing after resize.

2022-01-24 20:35 UTC, teesloane commented
I manually compressed the resized images and they are all now smaller. Our light house score on the caching page (picked to match what @nramabad posted above) has not improved; it has gotten worse:

![image](https://user-images.githubusercontent.com/12987958/150860367-6955126b-f538-45c8-a9f7-e2cc3ae6faa2.png)

However, the callout to "properly size images" was not on my report, so at least that seems improved.

2022-01-24 21:30 UTC, rsylvian approved these changes
LGTM ✅  Glad TinyPNG worked!

🚢  🇮🇹

2022-01-24 21:39 UTC, nramabad approved these changes
LGTM!

2022-01-24 22:12 UTC, merged