[DRAFT][DD-423] Experiment: Add cta buttons to "first-steps".
circleci/circleci-docs pull request #6447
Opened 2022-03-01 15:26 UTC by teesloane

[Ticket](https://circleci.atlassian.net/browse/DD-423)

Todo still:

- [ ] setup experiment
- [ ] Add link tracking
- [ ] figure out how to fix `li` order breaking (the inner `<div>` causes the incrementing of `li` to restart
- [ ] remove import of scss file into JS, into main scss system (this was just for easier / quick development.

2022-03-01 15:27 UTC, teesloane commented on jekyll/_layouts/classic-docs.html
> +        <div class="article-container docs {{page.title | slugify}}" id="main">
This was done so that we can easily scope scss to specific pages without worrying about breaking other things.

2022-03-01 22:59 UTC, tshen815 commented on src/js/experiments/signupLinksCta.js
> +window.OptimizelyClient.getVariationName({
Could we add the link to Optimizely here?

2022-03-01 23:01 UTC, tshen815 commented on src/js/experiments/signupLinksCta.js
> +  guestExperiment: true,
I dont think we are running this experiment on guest users? If we are only running this experiment on signed in users we can omit `guestExperiment` or set it to false

2022-03-02 01:01 UTC, chantelle11 commented on src/styles/_first_steps_cta.scss
> +  height: 54px;
Design shows 48px [link](https://www.figma.com/file/HrgpUU2M3ED7OT0p0f99bH/Docs-Disco-Experiments?node-id=5520%3A11933)

2022-03-02 01:02 UTC, chantelle11 commented on src/js/experiments/signupLinksCta.js
> +    $(".signup-and-try-experiment-block").toggleClass("show");
good idea!

2022-03-02 01:03 UTC, chantelle11 commented on src/js/experiments/signupLinksCta.js
> +      window.AnalyticsClient.trackAction("dd_first-steps-signup-cta_test", {
Should we include 'track-signup-link' to the drop down links? or does this account for those already

2022-03-02 01:04 UTC, chantelle11 commented on jekyll/_cci2/first-steps.md
> +    <!-- start: experiment code - #docs-discovery -->
I like this idea but will need them on the above buttons

2022-03-02 01:06 UTC, chantelle11 reviewed
Suggest we check the small view design with Dan. I would think maybe a stacking view? ie. column vs row

<img width="490" alt="Screen Shot 2022-03-01 at 8 05 19 PM" src="https://user-images.githubusercontent.com/86666932/156275010-5872dc01-ceb7-4096-9743-6e6355f069fe.png">

<img width="767" alt="Screen Shot 2022-03-01 at 8 05 34 PM" src="https://user-images.githubusercontent.com/86666932/156275040-fe3df52e-4745-46a8-8780-448c39bf5796.png">

2022-03-02 01:18 UTC, chantelle11 reviewed
Great work on this so far!!

2022-03-02 14:54 UTC, teesloane commented on src/styles/_first_steps_cta.scss
> +  height: 54px;
Thanks!

2022-03-02 15:57 UTC, tshen815 commented on src/js/experiments/signupLinksCta.js
> +  guestExperiment: true,
Its my mistake, you're totally right! I got confused and then I realized its CTA buttons.... 😅

2022-03-02 17:07 UTC, devinmarieb requested changes
Looks good! Just one comment on the copy on the page.

2022-03-02 17:07 UTC, devinmarieb commented on jekyll/_cci2/first-steps.md
> +By signing up, you are agreeing to our SaaS Agreement and Privacy Policy. We ask for read/write access to make your experience seamless on CircleCI. If you are a GitHub user and aren’t ready to share
There are no links here? If we are referencing legal documents, I would expect we need to link out to them. Specifically the SaaS Agreement, Privacy Policy, Google Privacy Policy, and Terms of Service.

2022-03-02 18:27 UTC, tshen815 requested changes
Looks great to me! 🤩 tested out locally and was able to see the experiment as a guest user.

Just a quick question, is the link for `workflows` support to go to circleci.com/docs or is it supposed to go to circleci.com/docs/2.0/workflows/?

<img width="880" alt="Screen Shot 2022-03-02 at 12 24 18 PM" src="https://user-images.githubusercontent.com/57234605/156424472-f7d6f701-f9f9-4f8d-9944-abbf8e6f296f.png">

2022-03-02 18:41 UTC, teesloane commented
> Looks great to me! 🤩 tested out locally and was able to see the experiment as a guest user. Mobile looks great as well :)
> 
> Just a quick question, is the link for `workflows` supposed to go to `circleci.com/docs` or is it supposed to go to `circleci.com/docs/2.0/workflows/`?
> 
> <img alt="Screen Shot 2022-03-02 at 12 24 18 PM" width="880" src="https://user-images.githubusercontent.com/57234605/156424472-f7d6f701-f9f9-4f8d-9944-abbf8e6f296f.png">

Interesting. I'm guessing not. I'll fix that even thought it's supposed to be a content-team fix.

2022-03-02 18:48 UTC, devinmarieb approved these changes

2022-03-02 18:51 UTC, tshen815 commented
> > Looks great to me! 🤩 tested out locally and was able to see the experiment as a guest user. Mobile looks great as well :)
> > Just a quick question, is the link for `workflows` supposed to go to `circleci.com/docs` or is it supposed to go to `circleci.com/docs/2.0/workflows/`?
> > <img alt="Screen Shot 2022-03-02 at 12 24 18 PM" width="880" src="https://user-images.githubusercontent.com/57234605/156424472-f7d6f701-f9f9-4f8d-9944-abbf8e6f296f.png">
> 
> Interesting. I'm guessing not. I'll fix that even thought it's supposed to be a content-team fix.

Ah wasnt sure if that was a content fix or something that was apart of the dev work. Thanks for addressing it 👍

2022-03-02 18:52 UTC, tshen815 approved these changes

2022-03-02 20:20 UTC, merged