add new migrations phases info
circleci/circleci-docs pull request #6867
Opened 2022-05-27 13:52 UTC by rosieyohannan

# Description
Add new migration planning information to the migrations Intro doc, and convert to asciidoc

# Reasons
[A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.
](https://circleci.atlassian.net/browse/DOCSTEAM-191?atlOrigin=eyJpIjoiNzMyOWY5YjQ1OTllNDdjOGExM2RhMGI0NTIwYTAyYmMiLCJwIjoiaiJ9)
# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: https://circleci.com/docs/style/.

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2022-05-27 15:00 UTC, brianoh1979 requested changes
Looks great! But I'd suggest the following minor changes:

(1) Underneath the list of 'Here are some basic resources to get you started' , the existing line "Enroll in the [migrationscourse](https://academy.circleci.com/arm-course?access_code=public-2021)
with CircleCI Academy to learn more about migrating to CircleCI." can be added preceded by the words 'You can also'.

I think that it is better here than at the very end.

(2) At the start of the "Migrating projects" section, the line beginning with "Any Jenkins project can be migrated...." should begin with "As an example, any Jenkins project can be migrated...." .

I would also change the title to "Project Migration Methodology" . 

(3) In the final section entitled "Next Steps", I would change the title to "Product-specific migration references"

2022-05-31 09:56 UTC, brianoh1979 commented
Okay, all looks good to me!

2022-05-31 17:02 UTC, kbatuigas requested changes
Just some minor suggestions!

2022-05-31 18:00 UTC, rosieyohannan commented on jekyll/_cci2/migration-intro.adoc
> +The first phase in our journey is the Assess phase. This is where you’ll take stock of your current landscape, and understand the differences between CircleCI functionality and that of your current C
```suggestion
Take stock of the current landscape, and understand the differences between CircleCI functionality and that of your current CI tool.
```

2022-05-31 18:01 UTC, rosieyohannan commented on jekyll/_cci2/migration-intro.adoc
> +-   Ask end-users to avoid changing anything during the transition
```suggestion
-   Ask end users to avoid changing anything during the transition
```

2022-06-02 10:35 UTC, brianoh1979 approved these changes
This all looks good to me!

2022-06-03 13:43 UTC, merged