updates to standardise execution env use pages - docker
circleci/circleci-docs pull request #6911
Opened 2022-06-07 13:58 UTC by rosieyohannan

# Description
Updating "Using ..." pages for all execution environments to standardise how this information is formatted and presented. This is the Docker PR, there will be a PR for each execution environment.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: https://circleci.com/docs/style/.

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [x] Break up walls of text by adding paragraph breaks.
- [x] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [x] Keep the title between 20 and 70 characters.
- [x] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [x] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [x] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [x] Include relevant backlinks to other CircleCI docs/pages.

2022-06-16 21:27 UTC, rosieyohannan commented on jekyll/_cci2/using-docker.md
> +{: Specifying Docker images }
```suggestion
{: #specifying-docker-images }
```

2022-06-21 20:01 UTC, kbatuigas requested changes
Just a couple comments!

2022-06-22 22:06 UTC, rosieyohannan commented on jekyll/_cci2/using-docker.md
> +A container is an instance of a specified Docker image. The first image listed in your configuration for a job is referred to as the _primary_ container image, and this is where all steps in the job
```suggestion
A container is an instance of a specified Docker image. The first image listed in your configuration for a job is referred to as the _primary_ container image and this is where all steps in the job will run. _Secondary_ containers can also be specified to run alongside for running services, such as, databases. If you are new to Docker, see the [Docker Overview documentation](https://docs.docker.com/engine/docker-overview/) for concepts.
```

2022-06-22 22:06 UTC, rosieyohannan commented on jekyll/_cci2/using-docker.md
> +CircleCI maintains convenience images on Docker Hub for popular languages. See [the CircleCI Developer Hub](https://circleci.com/developer/images) for a complete list of image names and tags.
```suggestion
CircleCI maintains convenience images on Docker Hub for popular languages. See [the CircleCI Developer Hub](https://circleci.com/developer/images) for a complete list of image names and tags.
```

2022-06-28 18:25 UTC, kbatuigas approved these changes
🎉

2022-06-28 21:56 UTC, merged