[SERVER-1894] Docs Update - Github secrets provisioning
circleci/circleci-docs pull request #6964
Opened 2022-06-14 14:33 UTC by circlery

# Description
Updates docs to handle new github secrets provisioning methods.

# Reasons
server-1894

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: https://circleci.com/docs/style/.

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2022-06-14 18:49 UTC, atulsingh0 commented
@circlery It would be great if we can add "helm snippet" as well when the customer creates the secret. 
```
github:
  clientId:  ""
  clientSecret:  ""
```

and if enterprise

```
github:
  clientId:  ""
  clientSecret:  ""
  defaultToken: ""
```

2022-06-15 21:54 UTC, lloydChris requested changes
Can this match the structure that we have established above (https://github.com/circleci/circleci-docs/blob/4.0/server-preview/jekyll/_cci2/server/Installation/2-install-core.adoc#api-token) ?

2022-06-16 22:25 UTC, rosieyohannan commented
Hello! Sorry I've made some changes to the filenames in the main branch for these changes so if you need help sorting out the conflicts let me know.

2022-06-22 16:24 UTC, lloydChris commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
> +You created your Github OAuth application in the prerequisite phase. Add the client ID and secret to
```suggestion
Add the client ID and secret to 
```

2022-06-22 16:26 UTC, lloydChris commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
> +  --from-literal=clientSecret=<github-client-secret>
I think it makes sense to be consistent with the naming, could go the other way too, i have not strong opinion on that

```suggestion
  --from-literal=clientId=<client-id> \
  --from-literal=clientSecret=<client-secret> 
```

2022-06-22 16:26 UTC, lloydChris commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
> +  --from-literal=defaultToken=<github-default-token>
```suggestion
  --from-literal=clientId=<client-id> \
  --from-literal=clientSecret=<client-secret> \
  --from-literal=defaultToken=<default-token>
```

2022-06-22 16:29 UTC, lloydChris commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
> +You created your Github OAuth application in the prerequisite phase. Add `clientID`, `clientSecret` and `defaultToken` to
```suggestion
Add `clientID`, `clientSecret` and `defaultToken` to 
```

2022-06-22 16:54 UTC, lloydChris commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
> +In GitHub, Create the `defaultToken` by navigating to **Settings > Developer Settings > Personal access tokens**. The default token requires no scopes.
```suggestion
In GitHub, Create the `defaultToken` by navigating to **Settings > Developer Settings > Personal access tokens**. The default token requires no scopes.  You will also need the client ID and secret you created with your Github OAuth application in the prerequisite phase.
```

2022-06-27 14:32 UTC, lloydChris approved these changes

2022-06-27 15:52 UTC, ryanwohara commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
>  === GitHub enterprise
```suggestion
=== GitHub Enterprise
```

2022-06-27 15:53 UTC, ryanwohara commented on jekyll/_cci2/server/Installation/phase-2-core-services.adoc
> +== Step Five: Object storage
```suggestion
== Step five: Object storage
```

2022-06-27 22:02 UTC, merged