feat: Proxies for server 4
circleci/circleci-docs pull request #7041
Opened 2022-07-01 14:28 UTC by ryanwohara

# Description

Documenting proxy usage in a 4.x environment.

# Reasons

https://circleci.atlassian.net/browse/SERVER-1840

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: https://circleci.com/docs/style/.

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2022-07-01 14:29 UTC, ryanwohara commented on jekyll/_cci2/server/operator/installing-server-behind-a-proxy.adoc
>  * If your GitHub instance is running outside of the proxied environment (either GitHub.com or GitHub Enterprise), you must ensure that SSH traffic from our application (inside the Kubernetes cluster)
This bullet point needs help. We cannot proxy ssh-keyscan but we can technically proxy SSH itself.

2022-07-13 13:43 UTC, atulsingh0 commented on jekyll/_cci2/server/operator/installing-server-behind-a-proxy.adoc
> +      password: circleciforever
```suggestion
      username: <proxy-user>
      password: <proxy-password>
```

2022-07-13 13:43 UTC, atulsingh0 commented on jekyll/_cci2/server/operator/installing-server-behind-a-proxy.adoc
> +    - 10.0.0.0/16 # Subnets to exclude from the proxy (optional)
```suggestion
    - <vpc-or-subnet-cidr>   # VPC or Subnets to exclude from the proxy (optional)
```

2022-07-13 14:03 UTC, lloydChris requested changes
--We have given yaml snippets (instead of ex. 'proxy.https.host`) everywhere else, do we want to do that here?--

Both for consistency and so customers can copy paste?

2022-07-13 14:17 UTC, lloydChris commented on jekyll/_cci2/server/operator/installing-server-behind-a-proxy.adoc
> +    - <vpc-or-subnet-cidr>   # VPC or subnets to exclude from the proxy (optional)
Should we make a suggestion to put nomad subnets in here, or are those covered by something else?

2022-07-13 14:17 UTC, lloydChris commented on jekyll/_cci2/server/operator/installing-server-behind-a-proxy.adoc
> +* If your GitHub instance is running outside of the proxied environment (either GitHub.com or GitHub Enterprise), you must ensure that SSH traffic from our application (inside the Kubernetes cluster)
NIT:
```suggestion
* If your GitHub instance is running outside of the proxied environment (either GitHub.com or GitHub Enterprise), you must ensure that SSH traffic from CircleCI (inside the Kubernetes cluster) and from our Nomad node can reach your instance. Please note the default `checkout` step in a CircleCI job will fail to clone code and our `ssh-keyscan` of GitHub Enterprise will not work. While you may configure an SSH proxy, `ssh-keyscan` can NOT be proxied and instead will require you provide `github.fingerprint` when using GHE.
```

2022-07-13 17:28 UTC, atulsingh0 approved these changes

2022-07-13 17:29 UTC, lloydChris approved these changes
👍

2022-07-13 22:24 UTC, rosieyohannan commented
@circleci/server where should we link to this guide from in the main installation guide? At which point do they need to decide this?

2022-07-14 14:03 UTC, ryanwohara commented
@rosieyohannan Maybe under prerequisites? 🤔 
We need the proxy information to deploy the cluster so that makes sense to me

2022-07-15 10:56 UTC, merged