[SERVER-1954] Remove references to prometheus
circleci/circleci-docs pull request #7106
Opened 2022-07-15 19:07 UTC by jbialy

# Description

By default we ship with telegraf which provides aggregated component metrics in prometheus format. The telegraf pod can be scraped if needed but including Prometheus as part of the server stack is out of scope so let's leave it disabled.

# Reasons

https://circleci.atlassian.net/browse/SERVER-1954

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: https://circleci.com/docs/style/.

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2022-07-15 19:27 UTC, lloydChris requested changes

2022-07-16 00:05 UTC, jbialy commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> -** prometheus (circleci-server-kube-state-metrics, node-exporter,prometheus-server)
Good point!

2022-07-18 15:31 UTC, jbialy commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> -** prometheus (circleci-server-kube-state-metrics, node-exporter,prometheus-server)
See https://github.com/circleci/circleci-docs/pull/7106/commits/ad5c7e481977b1010e4fcd1d4e5767dc751512d5 :)

2022-07-18 15:38 UTC, lloydChris approved these changes

2022-07-18 16:12 UTC, ryanwohara approved these changes

2022-07-19 10:47 UTC, rosieyohannan approved these changes

2022-07-19 10:47 UTC, merged