server-1943 | added filters in aws commands
circleci/circleci-docs pull request #7259
Opened 2022-08-16 13:25 UTC by atulsingh0

# Description
* Add filter in AWS commands to output the information customer required

# Reasons
[SERVER-1943](https://circleci.atlassian.net/browse/SERVER-1943)

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2022-08-16 13:36 UTC, rosieyohannan approved these changes

2022-08-16 15:14 UTC, lloydChris requested changes
Templating should use lower case and hyphens, one might even call it "non screaming kabab case". https://circleci.com/docs/style/using-code-samples

Also, we probably don't need to prefix things with "your".  But maybe that is a nit?  Or maybe @rosieyohannan knows the rule?

2022-08-16 15:14 UTC, lloydChris commented on jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
> +aws eks describe-cluster --name=<YOUR_CLUSTER_NAME> --query "cluster.resourcesVpcConfig.vpcId" -output text | xargs
```suggestion
aws eks describe-cluster --name=<cluster-name> --region=<region> --query "cluster.resourcesVpcConfig.vpcId" --output text | xargs
```

2022-08-16 15:35 UTC, lloydChris requested changes
I think we should include some regions in the commands, otherwise many of them return empty instead of a suggestion that the user should add the region

2022-08-16 15:35 UTC, lloydChris commented on jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
> +aws ec2 describe-vpcs --filters Name=vpc-id,Values=<YOUR_VPCID> --query "Vpcs[].CidrBlock" --output text | xargs
```suggestion
aws ec2 describe-vpcs --filters Name=vpc-id,Values=<YOUR_VPCID> --query "Vpcs[].CidrBlock" --output text --region=<region> | xargs
```

2022-08-16 15:35 UTC, lloydChris commented on jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
> +aws eks describe-cluster --name=<YOUR_CLUSTER_NAME> --query "cluster.resourcesVpcConfig.vpcId" --output text | xargs
```suggestion
aws eks describe-cluster --name=<YOUR_CLUSTER_NAME> --query "cluster.resourcesVpcConfig.vpcId" --output text --region=<region> | xargs
```

2022-08-16 15:35 UTC, lloydChris commented on jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
> +aws ec2 describe-subnets --subnet-ids=<NOMAD_SUBNET_ID> --query "Subnets[*].[SubnetId, CidrBlock]" | xargs
```suggestion
aws ec2 describe-subnets --subnet-ids=<NOMAD_SUBNET_ID> --region=<region> --query "Subnets[*].[SubnetId, CidrBlock]" | xargs
```

2022-08-16 16:05 UTC, lloydChris requested changes

2022-08-16 16:05 UTC, lloydChris commented on jekyll/_cci2/server/installation/phase-3-execution-environments.adoc
> +<<<<<<< HEAD
maybe missed this on the merge?

2022-08-17 13:48 UTC, lloydChris approved these changes

2022-08-18 14:18 UTC, merged