Server-2047 | Simplified flyway & postgres chart migration
circleci/circleci-docs pull request #7305
Opened 2022-08-30 14:48 UTC by atulsingh0

# Description
* Removed Postgres chart migrations Instructions as those will be executed as migration script
* `circle-migrator` job will be automatically deleted if completed successfully. 

# Reasons
[SERVER-2047](https://circleci.atlassian.net/browse/SERVER-2047)

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2022-08-30 15:45 UTC, jbialy commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> +Else, contact with your circleci point of contact for further instructions.
```suggestion
Else, reach out to your circleci point of contact for further instructions.
```

2022-09-02 14:20 UTC, circlery commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> +[source,shell]
is shell highlighting the best here?

2022-09-02 14:23 UTC, circlery requested changes

2022-09-02 14:23 UTC, circlery commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> +If job does not exists then check the pod log `circle-migrator.log` in `log` directory and pod log can be is look like below -
```suggestion
If the job does not exist, check the pod's logs `circle-migrator.log` in the `log` directory. An example of the logs can be found below.
```

2022-09-02 14:23 UTC, circlery commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> +Else, reach out to your circleci point of contact for further instructions.
```suggestion
For any other concerns, please reach out to your CircleCI point of contact.
```

Do we actually even need this sentence?

2022-09-02 15:08 UTC, circlery approved these changes
Thanks for the changes! LGTM.

2022-09-06 12:01 UTC, rosieyohannan commented on jekyll/_cci2/server/installation/migrate-from-server-3-to-server-4.adoc
> +If the job does not exist, check the pod's logs `circle-migrator.log` in the `log` directory. An example of the logs can be found below.
```suggestion
If the job does not exist, check the pod's logs (`circle-migrator.log`) in the `log` directory. An example of the logs can be found below:
```

2022-09-06 21:01 UTC, rosieyohannan approved these changes
Thank you @atulsingh0!

2022-09-06 21:01 UTC, merged