Move metal xcode versions to their own table
circleci/circleci-docs pull request #7506
Opened 2022-10-24 11:51 UTC by BytesGuy

# Description
Move metal xcode versions to their own table

# Reasons
Increase clarity over which versions are available to which resource classes and reduce clutter in the main Xcode versions table

2022-10-24 20:55 UTC, devinmarieb commented
@BytesGuy Hey, the build is failing. It looks like you didn't rename the file in the Japanese snippets folder from `xcode-versions.md` to `xcode-intel-vm.md` before you started referencing it in the Japanese pages.

2022-10-25 14:47 UTC, devinmarieb requested changes
See comment - there is a file that has an incorrect name.

2022-10-27 16:00 UTC, devinmarieb approved these changes

2022-10-27 22:56 UTC, Mayuko-Sa approved these changes

2022-10-28 12:20 UTC, merged