Docs for server 4.1
circleci/circleci-docs pull request #7648
Opened 2022-12-20 21:29 UTC by rosieyohannan

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-03-14 11:09 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.1/installation/phase-1-prerequisites.adoc
> +* xref:server/v4.1/installation/phase-2-core-services#[Phase 2: Core Services Installation].
@rsylvian here's an example of a cross reference. This works fine to get to: `circleci.com/docs/server/v4.1/installation/phase-2-core-services/` but fails the html proofer

2023-03-22 16:17 UTC, kbatuigas requested changes

2023-03-22 16:17 UTC, kbatuigas commented on jekyll/_data/sidenav.yml
> +            link: server/v4.1/overview/circleci-server-v4-overview
The filename doesn't have v4

2023-03-22 18:53 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/air-gapped-installation/phase-3-install-circleci-server.adoc
> +    org: "circleci"
```suggestion
    org: "<image-registry-org>"
```

2023-03-22 18:54 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/air-gapped-installation/example-values.yaml.adoc
> +    org: "circleci"
```suggestion
    org: "<image-registry-org>"
```

2023-03-22 22:26 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.1/air-gapped-installation/phase-2-configure-object-storage.adoc
> +1.0.137184-db08738f
I've moved the contents of this code block into the regular text, but yes `1.0.137184-db08738f` doesn't match what's in the screenshot. I imagine this is just incorrect/left over from a previous iteration. @circlery should these numbers match? I will update the one in the text to match the screenshot if so :-D

2023-03-22 22:28 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.1/air-gapped-installation/phase-2-configure-object-storage.adoc
> +# The structure of the directory should now look like this
Yeah that will work, I'll update 👍

2023-03-22 22:39 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +NOTE: After server 3.x to 4.x migration, You must rerun the Nomad terraform with modified value of 'server_endpoint' variable
ooo good spot, I imagine so!

2023-03-22 22:43 UTC, rosieyohannan commented on jekyll/_data/sidenav.yml
> +      - name: Server v4.1 installation
Oh yeah good spot! Must have just been missed off. I'll add in for 4.1 and fix 4.0 separately

2023-03-23 14:23 UTC, circlery commented on jekyll/_cci2/server/v4.1/air-gapped-installation/phase-2-configure-object-storage.adoc
> +1.0.137184-db08738f
The numbers should match whatever is the latest in release.txt which is currently `1.0.164633-f867f14f`. 

It's in a code block to highlight the hierarchy of the file structure - but if there's a better way to do this please feel free to modify it.

2023-03-23 14:25 UTC, circlery commented on jekyll/_cci2/server/v4.1/air-gapped-installation/additional-considerations.adoc
> +- Potentially all K3s nodes in the air-gapped environment, if using docker-backed K3s
@atulsingh0 This won't be possible without modifying several other sections downstream. This airgapped tutorial uses K3s as a kubernetes provider, and it's unfortunately not as simple as removing the reference.

2023-03-23 14:25 UTC, circlery approved these changes

2023-03-23 17:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.1/overview/circleci-server-overview.adoc
> += CircleCI server v{serverversion41} overview
One last thing - not sure how this works but this shows up wonky for me

![image](https://user-images.githubusercontent.com/36839689/227302649-608aed85-bbf0-4f73-a422-6fe637c85943.png)

2023-03-23 18:28 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/overview/circleci-server-overview.adoc
> +* xref:../installation/phase-1-prerequisites#[Server 4.x Installation Prerequisites]
```suggestion
* xref:../installation/phase-1-prerequisites#[Server 4.1 Installation Prerequisites]
```

2023-03-23 18:52 UTC, kbatuigas approved these changes
Just one nit, but approved 🎉

2023-03-23 18:52 UTC, kbatuigas commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +NOTE: After server 3.x to 4.x migration, You must rerun the Nomad terraform with modified value of 'server_endpoint' variable
```suggestion
NOTE: After server 3.x to 4.x migration, you must rerun the Nomad terraform with the modified value of the `server_endpoint` variable. It should be - `<domain-name>:4647`.
```
I actually missed this commit, sorry

2023-03-23 18:52 UTC, kbatuigas commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +It should be - <domain-name>:4647
```suggestion

```

2023-03-23 19:37 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/operator/operator-overview.adoc
> +and VM service.
```suggestion
CircleCI server schedules CI/CD jobs using the https://www.nomadproject.io/[Nomad] scheduler. The Nomad Server (control plane) runs inside the Kubernetes cluster, while Nomad clients are provisioned outside the cluster. The Nomad clients need access to the Nomad control plane, output processor, and VM service.
```

2023-03-23 19:47 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/operator/introduction-to-nomad-cluster-operation.adoc
> +kubectl exec -it nomad-server-pod-ID -- nomad node-status
```suggestion
kubectl exec -it <<nomad-server-pod-ID>> -- nomad node-status
```

2023-03-23 20:04 UTC, atulsingh0 approved these changes

2023-03-23 20:45 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +helm diff upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml --show-secrets --context 5 oci://cciserver.azurecr.io/circleci-server --version 4.0.1
```suggestion
helm diff upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml --show-secrets --context 5 oci://cciserver.azurecr.io/circleci-server --version 4.0.2
```

2023-03-23 20:46 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +helm upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml oci://cciserver.azurecr.io/circleci-server --version <version-to-upgrade-to> --force
```suggestion
helm upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml oci://cciserver.azurecr.io/circleci-server --version 4.0.2 --force
```

2023-03-23 20:49 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +helm diff upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml --show-secrets --context 5 oci://cciserver.azurecr.io/circleci-server --version 4.0.1
```suggestion
helm diff upgrade <release-name> -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml --show-secrets --context 5 oci://cciserver.azurecr.io/circleci-server --version 4.0.2
```

2023-03-23 20:49 UTC, atulsingh0 commented on jekyll/_cci2/server/v4.1/installation/migrate-from-server-3-to-server-4.adoc
> +helm upgrade circleci-server -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml oci://cciserver.azurecr.io/circleci-server --version 4.0.1 --force
```suggestion
helm upgrade circleci-server -n <namespace> -f <path>/kots-exporter/output/helm-values.yaml oci://cciserver.azurecr.io/circleci-server --version 4.0.2 --force
```

2023-03-23 21:52 UTC, merged