Patch 159
circleci/circleci-docs pull request #7670
Opened 2023-01-10 15:53 UTC by devinmarieb

# Description
Updates to Sebastian's branch for preview.

# Reasons
First edit on the first draft.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-01-10 15:56 UTC, devinmarieb commented
@sebastian-lerner any new changes, please use this PR to edit the commits. I couldn't directly pull down your branch and keep using the same PR you had been working on, but if you look above you can still see your commit history here. I have two basic questions so far:

- In the FAQ section we only call out one orb, which is a little weird. If we have only tested one orb internally, I think we need to add a note that other orbs won't work, or we can't guarantee that other orbs will work.
- Do you already have the diagrams ready to be added in? If so I can add them in now. If not we can do it later.

2023-01-10 17:45 UTC, sebastian-lerner commented
@devinmarieb got it thank you!  we can add a note that other orbs haven't been tested. the reason i call out this orb is because it's a super common orb for running tests on circleci so i was trying to anticipate questions that were likely to come up.

diagrams are ready but let me know if you think they are good enough.  attaching them here

![fail_fast_without_splitting](https://user-images.githubusercontent.com/86729349/211624180-6a47f9e8-c555-4f9d-9733-2c5de0020f27.jpg)
![fail_fast_with_splitting](https://user-images.githubusercontent.com/86729349/211624297-d6ec8a3e-a024-4fb2-b86f-316868e32e74.jpg)

2023-01-10 17:46 UTC, sebastian-lerner commented
the images have different style...sorry...the first one i didn't create and i dont have the source.  and i'm not great at creating diagrams... should i try to refine them?

2023-01-10 19:11 UTC, devinmarieb commented
@sebastian-lerner These are fine for a preview. I think ideally they are refined for when the feature moves to GA

2023-01-10 20:54 UTC, sebastian-lerner commented
we may want to add a note that "plugin manager" is a circleci component that manages state between batches. i wish i could change the name on that box..."plugin manager" is confusing

2023-01-17 22:23 UTC, kbatuigas requested changes

2023-01-17 22:23 UTC, kbatuigas commented on jekyll/_cci2/fail-fast.adoc
> +== Motivation and Introduction
```suggestion
== Motivation and introduction
```

2023-01-17 22:23 UTC, kbatuigas commented on jekyll/_cci2/fail-fast.adoc
> +== Use Cases
```suggestion
== Use cases
```

2023-01-17 22:23 UTC, kbatuigas commented on jekyll/_cci2/fail-fast.adoc
> +Batches are groups of tests that have been divided, and will report status after completion. If a test failure is found when executing the group of tests in a given batch, the batch will return a fai
"**With fail-fast enabled**"? Or "**When fail-fast is enabled**"?

2023-01-17 22:23 UTC, kbatuigas commented on jekyll/_cci2/fail-fast.adoc
> +If no test splitting is enabled, batches execute sequentially as shown in the diagram shows below. ("Plugin Manager" is a CircleCI component that manages state between batches).
```suggestion
If no test splitting is enabled, batches execute sequentially as shown in the diagram below. ("Plugin Manager" is a CircleCI component that manages state between batches.)
```

2023-01-17 22:23 UTC, kbatuigas commented on jekyll/_cci2/fail-fast.adoc
> +As a developer, speeding up your CI feedback loop is an excellent way to stay in your flow. For jobs with lengthy running tests, where even one failed test requires immediate attention, waiting for f
```suggestion
For jobs with lengthy running tests, where even one failed test requires immediate attention, waiting for feedback until all tests have run to completion results in wasted time and unoptimized credit usage.
```
I think the first sentence can be dropped for conciseness.

2023-01-17 22:23 UTC, kbatuigas commented on jekyll/_cci2/fail-fast.adoc
> +Now in open preview is a new functionality to fail tests faster. You can configure your testing jobs to stop executing shortly after finding the first test failure.
I am leaning towards rephrasing the first sentence. Something along the lines of... "CircleCI is releasing in open preview a new functionality to fail tests faster." I think the "now" makes it sound more like marketing copy.

2023-01-19 19:44 UTC, kbatuigas approved these changes
🙌

2023-01-19 21:51 UTC, merged