How to remove a project
circleci/circleci-docs pull request #7771
Opened 2023-02-16 11:55 UTC by rosieyohannan

# Description
Add a page to detail how to remove a project from CircleCI

# Reasons
This content was missing

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-02-16 12:26 UTC, rosieyohannan commented on jekyll/_cci2/stop-building-a-project-on-circleci.adoc
> +This page provides details on how to stop builds for a project on CircleCI, and how to remove all projects data when required.
```suggestion
This page provides details on how to stop builds for a project on CircleCI, and how to remove all project data when required.
```

2023-02-16 23:11 UTC, rosieyohannan commented on jekyll/_cci2/stop-building-a-project-on-circleci.adoc
> +CAUTION: The **Stop Building** option will not automatically remove all project data from the CircleCI databases. To remove all project data from CircleCI you need to contact CIrcleCI support, as det
```suggestion
CAUTION: The **Stop Building** option will not automatically remove all project data from the CircleCI databases. To remove all project data from CircleCI you need to contact CircleCI support, as detailed in the <<remove-a-project-and-all-associated-data>> section.
```

2023-02-17 22:41 UTC, kbatuigas requested changes
Typo and a question

2023-02-18 00:17 UTC, kbatuigas approved these changes
🎉

2023-02-20 00:00 UTC, merged