add prepaid billing FAQs
circleci/circleci-docs pull request #7828
Opened 2023-03-06 11:40 UTC by rosieyohannan

# Description
Prepaid billing FAQs

![Screen Shot 2023-03-06 at 11 39 21](https://user-images.githubusercontent.com/24589403/223100431-bd6e7e78-1b99-4ea7-80e5-028591627ef5.png)

# Reasons
Prepaid Billing launch

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [x] Break up walls of text by adding paragraph breaks.
- [x] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [x] Keep the title between 20 and 70 characters.
- [x] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [x] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-03-06 11:41 UTC, rosieyohannan commented on jekyll/_includes/snippets/faq/architecture-faq-snip.adoc
> +You can use the xref:configuration-reference#machine[Machine executor] for testing local IPv6 traffic. Unfortunately, we do not support IPv6 internet traffic, as not all of our cloud providers offer
This link was broken and causing my local build to fail, which is odd cos it's not new!

2023-03-06 11:41 UTC, rosieyohannan commented on jekyll/_includes/snippets/faq/billing-faq-snip.adoc
> -[#share-plans-across-organizations-billed-centrally]
These are just moved further down

2023-03-06 11:42 UTC, rosieyohannan commented on jekyll/_includes/snippets/faq/billing-faq-snip.adoc
> -=== What happens when I run out of credits?
Moved up in the section for better flow

2023-03-06 11:43 UTC, rosieyohannan commented on jekyll/_includes/snippets/faq/billing-faq-snip.adoc
> +[#what-is-prepaid-billing]
New content from here to ......

2023-03-06 11:43 UTC, rosieyohannan commented on jekyll/_includes/snippets/faq/billing-faq-snip.adoc
> +
here

2023-03-06 18:26 UTC, kbatuigas requested changes
Just one suggestion!

2023-03-06 18:26 UTC, kbatuigas commented on jekyll/_includes/snippets/faq/billing-faq-snip.adoc
> +Prepaid Billing is a payment option for customers on Performance plan. Prepaid Billing allows you to purchase credits in bulk, pay upfront, and, based on volume purchased, be able to get discounted p
```suggestion
Prepaid Billing is a payment option for customers on the Performance plan. Prepaid Billing allows you to purchase credits in bulk, pay upfront, and be able to get discounted prices for credits based on volume purchased.
```
For easier reading

2023-03-07 16:12 UTC, kbatuigas approved these changes

2023-03-07 16:15 UTC, merged