Use variables in migration snippets
circleci/circleci-docs pull request #8009
Opened 2023-05-09 09:47 UTC by rosieyohannan

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-05-10 14:13 UTC, kbatuigas requested changes

2023-05-10 14:13 UTC, kbatuigas commented on jekyll/_cci2/server/installation/phase-4-post-installation.adoc
> +* link:/docs/server/installation/hardening-your-cluster[Hardening Your cluster]
```suggestion
* link:/docs/server/installation/hardening-your-cluster[Hardening your cluster]
```

2023-05-10 14:13 UTC, kbatuigas commented on jekyll/_cci2/server/installation/phase-2-core-services.adoc
> +helm install circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version {serverversion4}} -f <path-to-values.yaml>
```suggestion
helm install circleci-server oci://cciserver.azurecr.io/circleci-server -n $namespace --version {serverversion4} -f <path-to-values.yaml>
```

2023-05-15 14:45 UTC, kbatuigas approved these changes

2023-05-15 17:06 UTC, ryanwohara approved these changes

2023-05-15 17:07 UTC, soulchips approved these changes

2023-05-15 17:15 UTC, merged