add optimization overview to sidebar and refresh
circleci/circleci-docs pull request #8010
Opened 2023-05-09 13:36 UTC by rosieyohannan

# Description

I thought this would make a good reference page. The original ask in the ticket was to split this page up and make overview sections for the three optimization sections we have. I felt this wasn't the right thing to do at this time as we've been talking about making landing pages instead, so thought a reference page would work instead to find a place for the page

# Reasons
Optimizations overview was not on the sidebar.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-05-10 14:37 UTC, kbatuigas requested changes
Couple of edits

2023-05-10 17:20 UTC, rosieyohannan commented on jekyll/_cci2/optimizations.md
> +* CircleCI provides a range of [convenience images](/docs/circleci-images/#section=configuration), typically based on official Docker images, but with a range of useful language tools pre-installed.
```suggestion
* CircleCI provides a range of [convenience images](/docs/circleci-images/), typically based on official Docker images, but with a range of useful language tools pre-installed.
```

2023-05-10 17:20 UTC, rosieyohannan commented on jekyll/_cci2/optimizations.md
> +* You can create [custom images](/docs/custom-images/#section=configuration), maximizing specificity for your projects. To help with this we provide [guidance for building images manually](/docs/cust
```suggestion
* You can create [custom images](/docs/custom-images/), maximizing specificity for your projects. To help with this we provide [guidance for building images manually](/docs/custom-images/#creating-a-custom-image-manually).
```

2023-05-10 17:20 UTC, rosieyohannan commented on jekyll/_cci2/optimizations.md
> +{: dynamic-configuration}
```suggestion
{: #dynamic-configuration}
```

2023-05-15 14:01 UTC, kbatuigas approved these changes
🙌

2023-05-15 14:09 UTC, merged