[WIP] server 4.2 docs
circleci/circleci-docs pull request #8032
Opened 2023-05-18 10:42 UTC by rosieyohannan

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-07-18 18:59 UTC, kbatuigas requested changes
Mostly minor edits, a couple of (non-blocking IMO) suggestions

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/manage-virtual-machines-with-vm-service.adoc
> +The informaiton in this section describes post-installation configuration options for VM service.
```suggestion
The information in this section describes post-installation configuration options for VM service.
```

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/managing-orbs.adoc
> +This section describes how to manage orbs for an installation of server v4.x. Server installations include their own local orb registry. All orbs referenced in configs refer to the orbs in the server
Just checking if "server v4.x" needs to be changed to the specific version or if this typically uses a variable

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc
> +This document describes an initial set of troubleshooting steps to take if you are experiencing problems with your CircleCI server v4.x installation. If your issue is not addressed below, you can gen
Same comment regarding v4.x here

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc
> +=== Prerequisites
Missing section ID?

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/troubleshooting-and-support.adoc
> +=== Generating support bundle
Missing section ID?

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/upgrade-mongo.adoc
> +=== 1. Upgrade from MongoDB 3.6 to 4.0
Missing section ID?

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/upgrade-mongo.adoc
> +=== 2. Upgrade from MongoDB 4.0 to 4.2
Missing section ID?

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/upgrade-mongo.adoc
> +=== 3. Upgrade from MongoDB 4.2 to 4.4
Missing section ID?

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/usage-data-collection.adoc
> +## Current data collected
```suggestion
== Current data collected
```

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/operator/usage-data-collection.adoc
> +Currently, server v4.x does not include the data collection service. The service will be included in a future release.
Same question re: `v4.x` (vs `v4.2`) here

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/overview/circleci-server-overview.adoc
> +CircleCI server v4.x consists of the following services. Find their descriptions and failure implications below:
Same question re: v4.x (vs v4.2) here

2023-07-18 18:59 UTC, kbatuigas commented on jekyll/_cci2/server/v4.2/overview/release-notes.adoc
> +[#migraiton]
```suggestion
[#migration]
```

2023-07-18 20:49 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.2/air-gapped-installation/additional-considerations.adoc
> +CircleCI server makes use of Service Type: Load Balancer kubernetes resources to listen to traffic on multiple ports. In order to function, the cluster needs to.
@circlery could you take a look at this sentence?

2023-07-18 20:51 UTC, circlery commented on jekyll/_cci2/server/v4.2/air-gapped-installation/additional-considerations.adoc
> +CircleCI server makes use of Service Type: Load Balancer kubernetes resources to listen to traffic on multiple ports. In order to function, the cluster needs to.
```suggestion
CircleCI server makes use of Service Type: Load Balancer kubernetes resources to listen to traffic on multiple ports.
```

2023-07-18 20:51 UTC, circlery commented on jekyll/_cci2/server/v4.2/air-gapped-installation/additional-considerations.adoc
> +CircleCI server makes use of Service Type: Load Balancer kubernetes resources to listen to traffic on multiple ports. In order to function, the cluster needs to.
Let's remove this for now.

2023-07-18 20:52 UTC, circlery commented on jekyll/_cci2/server/v4.2/air-gapped-installation/phase-1-prerequisites.adoc
> +SERVER_4_1_IMAGE_LIST=`cat <<EOF
this needs updating with the list here:
https://circleci.atlassian.net/browse/SERVER-2554

2023-07-18 20:53 UTC, circlery commented on jekyll/_cci2/server/v4.2/air-gapped-installation/phase-1-prerequisites.adoc
> +echo $SERVER_4_1_IMAGE_LIST | while read -r image; do docker pull $image; done
this also needs updating with the list in the comment above

2023-07-18 21:03 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.2/operator/circleci-server-security-features.adoc
> +* Ensure you audit who has access to SSH keys in your organization.
```suggestion
* Ensure you regularly audit who has access to SSH keys in your organization.
```

2023-07-18 21:39 UTC, kbatuigas approved these changes

2023-07-18 21:57 UTC, rosieyohannan commented on jekyll/_cci2/server/v4.2/overview/release-notes.adoc
> +Server v4.2 introduces #TBC#
```suggestion
Server v4.2 introduces the config policies feature. Use config policies to create organization-level policies to impose rules and scopes to govern which configuration elements are required, allowed, not allowed etc.
```

2023-07-19 13:26 UTC, circlery approved these changes

2023-07-19 14:06 UTC, merged