How to guide for pull image from ECR using OIDC
circleci/circleci-docs pull request #8060
Opened 2023-05-25 10:35 UTC by rosieyohannan

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-05-25 16:05 UTC, sagar-connect approved these changes

2023-05-25 18:26 UTC, davidmdm commented on jekyll/_cci2/private-images.adoc
> +Alternatively, you can start use one of the following methods:
start *using*

2023-05-25 18:27 UTC, davidmdm approved these changes

2023-05-26 14:05 UTC, kbatuigas requested changes
Just minor changes

2023-05-26 14:05 UTC, kbatuigas commented on jekyll/_cci2/pull-an-image-from-aws-ecr-with-oidc.adoc
> +
```suggestion

[#introduction]
```

2023-05-26 14:05 UTC, kbatuigas commented on jekyll/_cci2/pull-an-image-from-aws-ecr-with-oidc.adoc
> +
```suggestion

[#prerequisites]
```

2023-05-26 14:05 UTC, kbatuigas commented on jekyll/_cci2/pull-an-image-from-aws-ecr-with-oidc.adoc
> +
```suggestion

[#set-up-iam-role]
```

2023-05-26 15:28 UTC, kbatuigas approved these changes

2023-05-26 16:33 UTC, merged