DEVEX-1240: Update VS Code docs about standalone projects
circleci/circleci-docs pull request #8276
Opened 2023-08-07 22:26 UTC by BeFunes

# Description
VS Code extension docs need to be adjusted to reflect accurately our support for standalone projects.
In this PR, I refer only to "Gitlab" projects, as I'm not sure what language will be used in Docs to refer to "Github projects created through Github app". I'd appreciate help on this! 

# Reasons
DevEx will soon ship support for Standalone project (without re-run with SSH and automatic project detection)
[DEVEX-1240](https://circleci.atlassian.net/browse/DEVEX-1240)

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

‼️ This PR should not be merged before [DEVEX-1174](https://circleci.atlassian.net/browse/DEVEX-1174) is shipped ⚠️

2023-08-29 15:52 UTC, kbatuigas requested changes
@BeFunes let me know how these sound!

2023-08-29 15:52 UTC, kbatuigas commented on jekyll/_cci2/get-started-with-the-vs-code-extension.adoc
> +NOTE: **Using GitLab?** The pipelines manager does not yet support automatic detection for GitLab projects. Please select your project manually from the settings page.
```suggestion
NOTE: **GitHub App and GitLab projects:** The pipelines manager does not yet support automatic detection for xref:github-apps-integration#[GitHub App] and xref:gitlab-integration#[GitLab] projects. Please select your project manually from the settings page.
```
In the changes we've made to other pages we refer to GitHub App and GitLab integrations, projects and/or users, and then we link to the integration pages which should help GitHub users determine whether they are on GH OAuth or GH App. Something like this should work... I think it's a bit less ambiguous compared to saying "Using GitHub App or GitLab?"

2023-08-29 15:52 UTC, kbatuigas commented on jekyll/_cci2/get-started-with-the-vs-code-extension.adoc
> +NOTE: **Using GitLab?** Re-run with SSH from VS Code is not yet enabled for Gitlab projects.
```suggestion
NOTE: **GitHub App and GitLab projects:** Re-run with SSH from VS Code is not yet enabled for xref:github-apps-integration#[GitHub App] and xref:gitlab-integration#[GitLab] projects.
```

2023-08-29 15:52 UTC, kbatuigas commented on jekyll/_cci2/vs-code-extension-overview.adoc
> +NOTE: **Using GitLab?** Re-run with SSH from VS Code is not yet enabled for Gitlab projects.
```suggestion
NOTE: **GitHub App and GitLab projects:** Re-run with SSH from VS Code is not yet enabled for xref:github-apps-integration#[GitHub App] and xref:gitlab-integration#[GitLab] projects.
```

2023-09-01 08:59 UTC, BeFunes commented
@kbatuigas followed all your suggestions, they are all much better than my initial draft. 

On our side the feature is shipped, so as far as I'm concerned this PR can be merged when you're comfortable with it!

2023-09-01 13:49 UTC, kbatuigas approved these changes
Sounds good @BeFunes ! I'll merge this on your behalf, thanks!

2023-09-05 09:26 UTC, merged