Document setup workflows and pipeline parameters
circleci/circleci-docs pull request #8322
Opened 2023-09-06 00:09 UTC by jkzilla

# Description
A brief description of the changes.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-09-06 04:44 UTC, kbatuigas commented on jekyll/_cci2/pipeline-variables.adoc
> +Please note: if using setup workflows, all pipeline parameters must be present in the subsequent configuration, even if calling with the API
I think I'd actually go for moving this note in a section further down the page - I'll add it as a suggestion :)

2023-09-06 06:30 UTC, kbatuigas requested changes

2023-09-06 06:30 UTC, kbatuigas commented on jekyll/_cci2/pipeline-variables.adoc
> +Please note: if using setup workflows, all pipeline parameters must be present in the subsequent configuration, even if calling with the API
```suggestion

```

2023-09-18 10:41 UTC, rosieyohannan approved these changes

2023-09-21 12:20 UTC, kbatuigas approved these changes

2023-09-25 05:54 UTC, merged

2023-10-30 19:42 UTC, jkzilla reviewed
Today 05:24
That text is unclear/misleading.
e.g. "all pipeline parameters must be present in the subsequent configuration, including in API calls" makes little sense; if anything, the opposite is true - you don't need to pass any parameters in the API calls because CircleCI will include them anyway, even if you didn't want them (which is how I found this out).

It should say something like:

When using setup workflows, where control is passed to a second configuration, all pipeline parameters that are declared in the setup workflow must also be declared (ideally with the same defaults) in the second configuration.
This is because, when the setup workflow passes control to a second configuration, the parameters passed *to* the setup workflow will be merged in with any parameters specified *by* the setup workflow's code before being passed to the second configuration.
i.e. in addition to any parameters that the setup workflow's code might deliberately pass, the second configuration can also receive any parameter(s) that the setup workflow can, itself, legally accept, so the second configuration must tolerate receiving them (even if it doesn't need them).

... and you also need to explain how conflicts are resolved.
e.g. if a user triggers the setup build with MyParameter=foo but the setup workflow passes MyParameter=bar in as a parameter to the subsequent configuration, which one takes precedence?
Or does that cause the build to fail?

In my opinion, this behaviour is gnarly enough to warrant its own "Pipeline parameters in dynamic configuration" section on the https://circleci.com/docs/pipeline-variables/ page.
Describe it "nicely" there (i.e. tell folks what they need to do in order to have an easy time of things), and then go into full details (including how conflicts are resolved) in https://circleci.com/docs/dynamic-config/#how-dynamic-config-works (and add a "for more details" link to that from the new section in https://circleci.com/docs/pipeline-variables/).

... and then link to the new "Pipeline parameters in dynamic configuration" section from everywhere else that needs it (everywhere I linked to in my previous message) so that user's can't reasonably claim "I didn't see that".

@rosieyohannan @kbatuigas the customer followed up with the above, thoughts?