Clarify install of Gateway API for container runner SSH reruns [ONPREM-608]
circleci/circleci-docs pull request #8485
Opened 2023-11-30 22:29 UTC by christian-stephen

# Description
A brief description of the changes.

Some clarification around the install of Envoy Gateway after some initial feedback.

# Reasons
A link to a GitHub and/or JIRA issue (if applicable).
Otherwise, a brief sentence about why you made these changes.

https://circleci.atlassian.net/browse/ONPREM-608

# Content Checklist
Please follow our style when contributing to CircleCI docs. Our style guide is here: [https://circleci.com/docs/style/style-guide-overview](https://circleci.com/docs/style/style-guide-overview).

Please take a moment to check through the following items when submitting your PR (this is just a guide so will not be relevant for all PRs) 😸:

- [ ] Break up walls of text by adding paragraph breaks.
- [ ] Consider if the content could benefit from more structure, such as lists or tables, to make it easier to consume.
- [ ] Keep the title between 20 and 70 characters.
- [ ] Consider whether the content would benefit from more subsections (h2-h6 headings) to make it easier to consume.
- [ ] Check all headings h1-h6 are in sentence case (only first letter is capitalized).
- [ ] Is there a "Next steps" section at the end of the page giving the reader a clear path to what to read next?
- [ ] Include relevant backlinks to other CircleCI docs/pages.

2023-11-30 22:54 UTC, ryanwohara requested changes

2023-11-30 22:54 UTC, ryanwohara commented on jekyll/_cci2/container-runner-installation.adoc
> +. Once all Gateway API prerequisites are installed and available, add the `agent.ssh.enabled = “true”` parameter to the container runner configuration:
Ah we should fix these magic quotes while we can

```suggestion
. Once all Gateway API prerequisites are installed and available, add the `agent.ssh.enabled = "true"` parameter to the container runner configuration:
```

2023-11-30 23:07 UTC, ryanwohara approved these changes

2023-12-01 17:11 UTC, rosieyohannan commented on jekyll/_cci2/container-runner-installation.adoc
> +CircleCI has tested, and currently supports link:https://gateway.envoyproxy.io/[Envoy Gateway] as an implementation for the link:https://gateway-api.sigs.k8s.io/[Gateway API]. Other link:https://gate
```suggestion
CircleCI has tested, and currently supports link:https://gateway.envoyproxy.io/[Envoy Gateway] as an implementation for the link:https://gateway-api.sigs.k8s.io/[Gateway API]. Other link:https://gateway-api.sigs.k8s.io/implementations/[Gateway API implementations] that support TCPRoute resources are likely to be compatible, but not all of these implementations have been tested, and therefore compatibility is not guaranteed. Our recommendation is to use Envoy Gateway as your implementation. Envoy Gateway is currently in beta and is under development.
```

2023-12-01 17:42 UTC, rosieyohannan approved these changes

2023-12-01 18:27 UTC, merged